from app.db import Session, Base, engine
from app.models import User, Card, Book

# Drop and rebuild tables
Base.metadata.drop_all(engine)
Base.metadata.create_all(engine)

db = Session()

# Insert books
db.add_all([
  Book(book_title= "Little Women",
            author= "Louisa May Alcott",
            isbn= 9781593081089,
            publisher= "Barnes & Noble",
            genre= "Literature",
            price= 8.95,
            year_published= 2009,
            description= "Generations of readers young and old, male and female, have fallen in love with Little Women",
            rating= 5,
            sold_copies= 3000,
            is_top_seller= True),

            Book(book_title= "Frankenstein",
            author= "Mary Shelley",
            isbn= 9780143131847,
            publisher= "Penguin Publishing Group",
            genre= "Literature",
            price= 8.95,
            year_published= 2018,
            description= "Mary Shelley's seminal novel of the scientist whose creation becomes a monster.",
            rating= 3,
            sold_copies= 250,
            is_top_seller= False),
           
 
            Book(book_title= "The Picture of Dorian Gray",
            author= "Oscar Wilde",
            isbn= 9781593080259,
            publisher= "Barnes & Noble",
            genre= "Literature",
            price= 7.95,
            year_published= 2003,
            description= "Oscar Wilde brings his enormous gifts for astute social observation and sparkling prose to The Picture of Dorian Gray",
            rating= 5,
            sold_copies= 3100,
            is_top_seller= True),

            Book(book_title= "Wuthering Heights",
            author= "Emily Bronte",
            isbn= 9780141439556,
            publisher= "Penguin Publishing Group",
            genre= "Fiction",
            price= 7.95,
            year_published= 2002,
            description= "Wuthering Heights is a wild, passionate story of the intense and almost demonic love.",
            rating= 3,
            sold_copies= 1000,
            is_top_seller= False),

            Book(book_title= "Treasure Island",
            author= "Robert Louis Stevenson",
            isbn= 9781593082475,
            publisher= "Barnes & Noble",
            genre= "Adventure",
            price= 7.95,
            year_published= 2005,
            description= "The most popular pirate story ever written in English, featuring one of literature's most beloved.",
            rating= 4,
            sold_copies= 800,
            is_top_seller= False),

            Book(book_title= "Fahrenheit 451: A Novel",
            author= "Ray Bradbury",
            isbn= 9781451673319,
            publisher= "Simon & Schuster",
            genre= "Literature",
            price= 13.99,
            description= "Guy Montag is a fireman. His job is to destroy the most illegal of commodities, the printed book.",
            year_published= 2012,
            rating= 4,
            sold_copies= 1500,
            is_top_seller= False),

            Book(book_title= "Alice's Adventures in Wonderland & Through The Looking Glass",
            author= "Lewis Carroll",
            isbn= 9781533653697,
            publisher= "CreateSpace Publishing",
            genre= "Childrens",
            price= 12.0,
            year_published= 2016,
            description= "The young Alice is bored in a too conventional world. But here goes a White Rabbit.",
            rating= 3,
            sold_copies= 900,
            is_top_seller= False),

            Book(book_title= "Peter Pan",
            author= "J.M.Barrie",
            isbn= 9780805072457,
            publisher= "Henry Holt and Co.",
            genre= "Childrens",
            price= 7.99,
            year_published= 2003,
            description= "Peter Pan, the mischievous boy who refuses to grow up.",
            rating= 5,
            sold_copies= 2300,
            is_top_seller= True),

            Book(book_title= "A Wrinkle in Time",
            author= "Madeleine L'Engle",
            isbn= 9780312367541,
            publisher= "Square Fish",
            genre= "Childrens",
            price= 6.99,
            year_published= 2007,
            description= "Out of this wild night, a strange visitor comes to the Murry house and beckons Meg.",
            rating= 3,
            sold_copies= 1350,
            is_top_seller= False),

            Book(book_title= "The Wizard of Oz",
            author= "L. Frank Baum",
            isbn= 9780141321028,
            publisher= "Penguin Publishing Group",
            genre= "Childrens",
            price= 7.99,
            year_published= 2008,
            description= "Dorothy thinks she is lost forever when a terrifying tornado crashes through Kansas.",
            rating= 4,
            sold_copies= 3600,
            is_top_seller= True),

            Book(book_title= "The Secret of the Old Clock (Nancy Drew Mystery Stories #1)",
            author= "Carolyn Keene",
            isbn= 9780448095011,
            publisher= "Applewood Books",
            genre= "Childrens",
            price= 8.99,
            year_published= 1991,
            description= "Nancy, unaided, seeks to find a missing will.",
            rating= 4,
            sold_copies= 750,
            is_top_seller= False),

            Book(book_title= "In Cold Blood",
            author= "Truman Capote",
            isbn= 9780679745587,
            publisher= "Knopf Doubleday Publishing Group",
            genre= "True), Crime",
            price= 14.95,
            year_published= 1994,
            description= "On November 15, 1959, in the small town of Holcomb, Kansas, four members of the Clutter family were savagely murdered.",
            rating= 3,
            sold_copies= 1200,
            is_top_seller= False),

            Book(book_title= "The Devil in the White City",
            author= "Erik Larson",
            isbn= 9780609608449,
            publisher= "Crown Publishers",
            genre= "True), Crime",
            price= 14.95,
            year_published= 1994,
            description= "Two men, each handsome and unusually adept at his chosen work, embodied an element of the great dynamic.",
            rating= 5,
            sold_copies= 4000,
            is_top_seller= True),

            Book(book_title= "Helter Skelter: The True), Story of the Manson Murders",
            author= "Vincent Bugliosi, Curt Gentry",
            isbn= 9780393322231,
            publisher= "W.W. Norton Company",
            genre= "True), Crime",
            price= 14.49,
            year_published= 2001,
            description= "In the summer of 1969, in Los Angeles, a series of brutal, seemingly random murders captured headlines across America.",
            rating= 3,
            sold_copies= 2700,
            is_top_seller= False),

            Book(book_title= "Zodiac: The Shocking True)",
            author= "Robert Graysmith",
            isbn= 9780425212189,
            publisher= "Penguin Publishing Group",
            genre= "True), Crime",
            price= 8.99,
            year_published= 2007,
            description= "A sexual sadist, the Zodiac killer took pleasure in torture and murder. His first victims were a teenage couple.",
            rating= 5,
            sold_copies= 3200,
            is_top_seller= True),

            Book(book_title= "The Road to Jonestown: Jim Jones and Peoples Temple",
            author= "Jeff Guinn",
            isbn= 9781476763835,
            publisher= "Simon & Schuster",
            genre= "True), Crime",
            price= 15.99,
            year_published= 2018,
            description= "In the 1950s, a young Indianapolis minister named Jim Jones preached a curious blend of the gospel and Marxism.",
            rating= 4,
            sold_copies= 1800,
            is_top_seller= False),

            Book(book_title= "The Talented Mr. Ripley",
            author= "Patricia Highsmith",
            isbn= 9780393332148,
            publisher= "W.W. Norton Company",
            genre= "Thriller",
            price= 12.95,
            year_published= 2008,
            description= "Since his debut in 1955, Tom Ripley has evolved into the ultimate bad boy sociopath.",
            rating= 4,
            sold_copies= 1500,
            is_top_seller= True),

            Book(book_title= "Murder on the Orient Express",
            author= "Agatha Christie",
            isbn= 9780007119318,
            publisher= "HarperCollins",
            genre= "Thriller",
            price= 8.99,
            year_published= 2007,
            description= "Just after midnight, a snowdrift stops the Orient Express in its tracks as it travels through the mountainous Balkans.",
            rating= 4,
            sold_copies= 900,
            is_top_seller= False),

            Book(book_title= "The Shining",
            author= "Stephen King",
            isbn= 9780450040184,
            publisher= "New English Library",
            genre= "Thriller",
            price= 14.99,
            year_published= 1980,
            description= "Jack Torrance's new job at the Overlook Hotel is the perfect chance for a fresh start.",
            rating= 4,
            sold_copies= 3400,
            is_top_seller= True),

            Book(book_title= "Gone Girl",
            author= "Gillian Flynn",
            isbn= 9780307588371,
            publisher= "Random House Publishing Group",
            genre= "Thriller",
            price= 14.99,
            year_published= 2014,
            description= "On a warm summer morning in North Carthage, Missouri, it is Nick and Amy Dunne’s fifth wedding anniversary.",
            rating= 3,
            sold_copies= 1700,
            is_top_seller= False),

            Book(book_title= "The Silence of Lambs",
            author= "Thomas Harris",
            isbn= 9780312924584,
            publisher= "St. Martin's Publishing Group",
            genre= "Thriller",
            price= 8.99,
            year_published= 1991,
            description= "Hannibal Lecter. The ultimate villain of modern fiction. Read the five-million-copy bestseller that scared the world silent.",
            rating= 4,
            sold_copies= 1250,
            is_top_seller= False)
])

db.commit()

# Insert users
db.add_all([
  User(name='Harold', username='alesmonde0', email='nwestnedge0@cbc.ca', password='password123'),
])

db.commit()

db.close()