from app.models import User
from app.db import Session, Base, engine
from app.models import User, Card, Book

# Drop and rebuild tables
Base.metadata.drop_all(engine)
Base.metadata.create_all(engine)

db = Session()

# Insert books
db.add_all([
  Book(book_title= "Little Women",
            author= "Louisa May Alcott",
            isbn= 9781593081089,
            publisher= "Barnes & Noble",
            genre= "Literature",
            price= 8.95,
            year_published= 2009,
            description= "Generations of readers young and old, male and female, have fallen in love with the March sisters of Louisa May Alcott’s most popular and enduring novel, Little Women. Here are talented tomboy and author-to-be Jo, tragically frail Beth, beautiful Meg, and romantic, spoiled Amy, united in their devotion to each other and their struggles to survive in New England during the Civil War.",
            rating= 5,
            sold_copies= 3000,
            is_top_seller= True),

            Book(book_title= "Frankenstein",
            author= "Mary Shelley",
            isbn= 9780143131847,
            publisher= "Penguin Publishing Group",
            genre= "Literature",
            price= 8.95,
            year_published= 2018,
            description= "Mary Shelley's seminal novel of the scientist whose creation becomes a monster.",
            rating= 3,
            sold_copies= 250,
            is_top_seller= False),
           
 
            Book(book_title= "The Picture of Dorian Gray",
            author= "Oscar Wilde",
            isbn= 9781593080259,
            publisher= "Barnes & Noble",
            genre= "Literature",
            price= 7.95,
            year_published= 2003,
            description= "Oscar Wilde brings his enormous gifts for astute social observation and sparkling prose to The Picture of Dorian Gray, his dreamlike story of a young man who sells his soul for eternal youth and beauty. This dandy, who remains forever unchanged—petulant, hedonistic, vain, and amoral—while a painting of him ages and grows increasingly hideous with the years, has been horrifying, enchanting, obsessing, even corrupting readers for more than a hundred years.",
            rating= 5,
            sold_copies= 3100,
            is_top_seller= True),

            Book(book_title= "Wuthering Heights",
            author= "Emily Bronte",
            isbn= 9780141439556,
            publisher= "Penguin Publishing Group",
            genre= "Fiction",
            price= 7.95,
            year_published= 2002,
            description= "Wuthering Heights is a wild, passionate story of the intense and almost demonic love between Catherine Earnshaw and Heathcliff, a foundling adopted by Catherine's father. After Mr Earnshaw's death, Heathcliff is bullied and humiliated by Catherine's brother Hindley and wrongly believing that his love for Catherine is not reciprocated, leaves Wuthering Heights, only to return years later as a wealthy and polished man. He proceeds to exact a terrible revenge for his former miseries. The action of the story is chaotic and unremittingly violent, but the accomplished handling of a complex structure, the evocative descriptions of the lonely moorland setting and the poetic grandeur of vision combine to make this unique novel a masterpiece of English literature.",
            rating= 3,
            sold_copies= 1000,
            is_top_seller= False),

            Book(book_title= "Treasure Island",
            author= "Robert Louis Stevenson",
            isbn= 9781593082475,
            publisher= "Barnes & Noble",
            genre= "Adventure",
            price= 7.95,
            year_published= 2005,
            description= "The most popular pirate story ever written in English, featuring one of literature's most beloved \"bad guys,\" Treasure Island has been happily devoured by several generations of boys — and girls — and grownups. Its unforgettable characters include: young Jim Hawkins, who finds himself owner of a map to Treasure Island, where the fabled pirate booty is buried; honest Captain Smollett, heroic Dr. Livesey, and the good-hearted but obtuse Squire Trelawney, who help Jim on his quest for the treasure; the frightening Blind Pew, double-dealing Israel Hands, and seemingly mad Ben Gunn, buccaneers of varying shades of menace; and, of course, garrulous, affable, ambiguous Long John Silver, who is one moment a friendly, laughing, one-legged sea-cook . . .and the next a dangerous pirate leader!",
            rating= 4,
            sold_copies= 800,
            is_top_seller= False),

            Book(book_title= "Fahrenheit 451: A Novel",
            author= "Ray Bradbury",
            isbn= 9781451673319,
            publisher= "Simon & Schuster",
            genre= "Literature",
            price= 13.99,
            description= "Guy Montag is a fireman. His job is to destroy the most illegal of commodities, the printed book, along with the houses in which they are hidden. Montag never questions the destruction and ruin his actions produce, returning each day to his bland life and wife, Mildred, who spends all day with her television \"family.\" But when he meets an eccentric young neighbor, Clarisse, who introduces him to a past where people didn't live in fear and to a present where one sees the world through the ideas in books instead of the mindless chatter of television, Montag begins to question everything he has ever known.",
            year_published= 2012,
            rating= 4,
            sold_copies= 1500,
            is_top_seller= False),

            Book(book_title= "Alice's Adventures in Wonderland & Through The Looking Glass",
            author= "Lewis Carroll",
            isbn= 9781533653697,
            publisher= "CreateSpace Publishing",
            genre= "Childrens",
            price= 12.0,
            year_published= 2016,
            description= "The young Alice is bored in a too conventional world. But here goes a White Rabbit, dressed in a frock coat with a pocket watch. Alice follows the hasty hare and falls into Wonderland, a fantasy world populated by peculiar creatures and governed by the wicked Queen of Hearts. A world where nothing makes sense!",
            rating= 3,
            sold_copies= 900,
            is_top_seller= False),

            Book(book_title= "Peter Pan",
            author= "J.M.Barrie",
            isbn= 9780805072457,
            publisher= "Henry Holt and Co.",
            genre= "Childrens",
            price= 7.99,
            year_published= 2003,
            description= "Peter Pan, the mischievous boy who refuses to grow up, lands in the Darling's proper middle-class home to look for his shadow. He befriends Wendy, John and Michael and teaches them to fly (with a little help from fairy dust). He and Tinker Bell whisk them off to Never-land where they encounter the Red Indians, the Little Lost Boys, pirates and the dastardly Captain Hook.",
            rating= 5,
            sold_copies= 2300,
            is_top_seller= True),

            Book(book_title= "A Wrinkle in Time",
            author= "Madeleine L'Engle",
            isbn= 9780312367541,
            publisher= "Square Fish",
            genre= "Childrens",
            price= 6.99,
            year_published= 2007,
            description= "Out of this wild night, a strange visitor comes to the Murry house and beckons Meg, her brother Charles Wallace, and their friend Calvin O'Keefe on a most dangerous and extraordinary adventure—one that will threaten their lives and our universe.",
            rating= 3,
            sold_copies= 1350,
            is_top_seller= False),

            Book(book_title= "The Wizard of Oz",
            author= "L. Frank Baum",
            isbn= 9780141321028,
            publisher= "Penguin Publishing Group",
            genre= "Childrens",
            price= 7.99,
            year_published= 2008,
            description= "Dorothy thinks she is lost forever when a terrifying tornado crashes through Kansas and whisks her and her dog, Toto, far away to the magical land of Oz. To get home Dorothy must follow the yellow brick road to Emerald City and find the wonderfully mysterious Wizard of Oz. Together with her companions the Tin Woodman, the Scarecrow and the Cowardly Lion whom she meets on the way, Dorothy embarks on a strange and enchanting adventure.",
            rating= 4,
            sold_copies= 3600,
            is_top_seller= True),

            Book(book_title= "The Secret of the Old Clock (Nancy Drew Mystery Stories #1)",
            author= "Carolyn Keene",
            isbn= 9780448095011,
            publisher= "Applewood Books",
            genre= "Childrens",
            price= 8.99,
            year_published= 1991,
            description= "Nancy, unaided, seeks to find a missing will. To the surprise of many, the Topham family will inherit wealthy Josiah Crowley's fortune, instead of deserving relatives and friends who were promised inheritances. Nancy determines that a clue to a second will might be found in an old clock Mr. Crowley had owned and she seeks to find the timepiece. Her search not only tests her keen mind, but also leads her into a thrilling adventure.",
            rating= 4,
            sold_copies= 750,
            is_top_seller= False),

            Book(book_title= "In Cold Blood",
            author= "Truman Capote",
            isbn= 9780679745587,
            publisher= "Knopf Doubleday Publishing Group",
            genre= "True), Crime",
            price= 14.95,
            year_published= 1994,
            description= "On November 15, 1959, in the small town of Holcomb, Kansas, four members of the Clutter family were savagely murdered by blasts from a shotgun held a few inches from their faces. There was no apparent motive for the crime, and there were almost no clues. In one of the first non-fiction novels ever written, Truman Capote reconstructs the murder and the investigation that led to the capture, trial, and execution of the killers, generating both mesmerizing suspense and astonishing empathy. In Cold Blood is a work that transcends its moment, yielding poignant insights into the nature of American violence.",
            rating= 3,
            sold_copies= 1200,
            is_top_seller= False),

            Book(book_title= "The Devil in the White City",
            author= "Erik Larson",
            isbn= 9780609608449,
            publisher= "Crown Publishers",
            genre= "True), Crime",
            price= 14.95,
            year_published= 1994,
            description= "Two men, each handsome and unusually adept at his chosen work, embodied an element of the great dynamic that characterized America's rush toward the twentieth century. The architect was Daniel Hudson Burnham, the fair's brilliant director of works and the builder of many of the country's most important structures, including the Flatiron Building in New York and Union Station in Washington, D.C. The murderer was Henry H. Holmes, a young doctor who, in a malign parody of the White City, built his \"World's Fair Hotel\" just west of the fairgrounds—a torture palace complete with dissection table, gas chamber, and 3,000-degree crematorium. ",
            rating= 5,
            sold_copies= 4000,
            is_top_seller= True),

            Book(book_title= "Helter Skelter: The True), Story of the Manson Murders",
            author= "Vincent Bugliosi, Curt Gentry",
            isbn= 9780393322231,
            publisher= "W.W. Norton Company",
            genre= "True), Crime",
            price= 14.49,
            year_published= 2001,
            description= "In the summer of 1969, in Los Angeles, a series of brutal, seemingly random murders captured headlines across America. A famous actress (and her unborn child), an heiress to a coffee fortune, a supermarket owner and his wife were among the seven victims. A thin trail of circumstances eventually tied the Tate-LeBianca murders to Charles Manson, a would-be pop singer of small talent living in the desert with his \"family\" of devoted young women and men. What was his hold over them? And what was the motivation behind such savagery? In the public imagination, over time, the case assumed the proportions of myth. The murders marked the end of the sixties and became an immediate symbol of the dark underside of that era.",
            rating= 3,
            sold_copies= 2700,
            is_top_seller= False),

            Book(book_title= "Zodiac: The Shocking True), Story of the Hunt for the Nation's Most Elusive Serial Killer",
            author= "Robert Graysmith",
            isbn= 9780425212189,
            publisher= "Penguin Publishing Group",
            genre= "True), Crime",
            price= 8.99,
            year_published= 2007,
            description= "A sexual sadist, the Zodiac killer took pleasure in torture and murder. His first victims were a teenage couple, stalked and shot dead in a lovers' lane. After another slaying, he sent his first mocking note to authorities, promising he would kill more. The official tally of his victims was six. He claimed thirty-seven dead. The real toll may have reached fifty.",
            rating= 5,
            sold_copies= 3200,
            is_top_seller= True),

            Book(book_title= "The Road to Jonestown: Jim Jones and Peoples Temple",
            author= "Jeff Guinn",
            isbn= 9781476763835,
            publisher= "Simon & Schuster",
            genre= "True), Crime",
            price= 15.99,
            year_published= 2018,
            description= "In the 1950s, a young Indianapolis minister named Jim Jones preached a curious blend of the gospel and Marxism. His congregation was racially mixed, and he was a leader in the early civil rights movement. Eventually, Jones moved his church, Peoples Temple, to northern California, where he got involved in electoral politics and became a prominent Bay Area leader. But underneath the surface lurked a terrible darkness.",
            rating= 4,
            sold_copies= 1800,
            is_top_seller= False),

            Book(book_title= "The Talented Mr. Ripley",
            author= "Patricia Highsmith",
            isbn= 9780393332148,
            publisher= "W.W. Norton Company",
            genre= "Thriller",
            price= 12.95,
            year_published= 2008,
            description= "Since his debut in 1955, Tom Ripley has evolved into the ultimate bad boy sociopath. Here, in the first Ripley novel, we are introduced to suave Tom Ripley, a young striver, newly arrived in the heady world of Manhattan. A product of a broken home, branded a \"sissy\" by his dismissive Aunt Dottie, Ripley meets a wealthy industrialist who hires him to bring his playboy son, Dickie Greenleaf, back from gallivanting in Italy. Soon Ripley's fascination with Dickie's debonair lifestyle turns obsessive as he finds himself enraged by Dickie's ambivalent affections for Marge, a charming American dilettante.",
            rating= 4,
            sold_copies= 1500,
            is_top_seller= True),

            Book(book_title= "Murder on the Orient Express",
            author= "Agatha Christie",
            isbn= 9780007119318,
            publisher= "HarperCollins",
            genre= "Thriller",
            price= 8.99,
            year_published= 2007,
            description= "Just after midnight, a snowdrift stops the Orient Express in its tracks as it travels through the mountainous Balkans. The luxurious train is surprisingly full for the time of the year but, by the morning, it is one passenger fewer. An American tycoon lies dead in his compartment, stabbed a dozen times, his door locked from the inside. One of the passengers is none other than detective Hercule Poirot. On vacation. Isolated and with a killer in their midst, Poirot must identify the murderer—in case he or she decides to strike again.",
            rating= 4,
            sold_copies= 900,
            is_top_seller= False),

            Book(book_title= "The Shining",
            author= "Stephen King",
            isbn= 9780450040184,
            publisher= "New English Library",
            genre= "Thriller",
            price= 14.99,
            year_published= 1980,
            description= "Jack Torrance's new job at the Overlook Hotel is the perfect chance for a fresh start. As the off-season caretaker at the atmospheric old hotel, he'll have plenty of time to spend reconnecting with his family and working on his writing. But as the harsh winter weather sets in, the idyllic location feels ever more remote...and more sinister. And the only one to notice the strange and terrible forces gathering around the Overlook is Danny Torrance, a uniquely gifted five-year-old.",
            rating= 4,
            sold_copies= 3400,
            is_top_seller= True),

            Book(book_title= "Gone Girl",
            author= "Gillian Flynn",
            isbn= 9780307588371,
            publisher= "Random House Publishing Group",
            genre= "Thriller",
            price= 14.99,
            year_published= 2014,
            description= "On a warm summer morning in North Carthage, Missouri, it is Nick and Amy Dunne’s fifth wedding anniversary. Presents are being wrapped and reservations are being made when Nick’s clever and beautiful wife disappears. Husband-of-the-Year Nick isn’t doing himself any favors with cringe-worthy daydreams about the slope and shape of his wife’s head, but passages from Amy's diary reveal the alpha-girl perfectionist could have put anyone dangerously on edge. Under mounting pressure from the police and the media—as well as Amy’s fiercely doting parents—the town golden boy parades an endless series of lies, deceits, and inappropriate behavior. Nick is oddly evasive, and he’s definitely bitter—but is he really a killer?",
            rating= 3,
            sold_copies= 1700,
            is_top_seller= False),

            Book(book_title= "The Silence of Lambs",
            author= "Thomas Harris",
            isbn= 9780312924584,
            publisher= "St. Martin's Publishing Group",
            genre= "Thriller",
            price= 8.99,
            year_published= 1991,
            description= "Hannibal Lecter. The ultimate villain of modern fiction. Read the five-million-copy bestseller that scared the world silent. The Silence of the Lambs. A young FBI trainee. An evil genius locked away for unspeakable crimes. A plunge into the darkest chambers of a psychopath's mind--in the deadly search for a serial killer.",
            rating= 4,
            sold_copies= 1250,
            is_top_seller= False)
])

db.commit()

# Insert users
db.add_all([
  User(name='Harold', username='alesmonde0', email='nwestnedge0@cbc.ca', password='password123'),
])

db.commit()

db.close()